Feature/dsnd 1796
companieshouse/company-profile-search-consumer pull request #15
Opened 2024-06-25 14:35 UTC by maddytjCH

- Add delete company profile
- Add happy path tests

2024-06-25 14:38 UTC, ch-code-analysis commented
CI: No security warnings found

2024-06-25 15:03 UTC, lbedrosyanCH requested changes

2024-06-25 15:03 UTC, lbedrosyanCH commented on src/main/java/uk/gov/companieshouse/companyprofile/search/consumer/SearchConsumer.java
> +        }
You should be calling a processDeleteMessage method here

2024-06-25 15:03 UTC, lbedrosyanCH commented on src/main/java/uk/gov/companieshouse/companyprofile/search/processor/SearchProcessor.java
> +        if (payload.getEvent().getType().equals("deleted")) {
This will never be true since the processChangedMessage method is only called if the type is changed

2024-07-09 09:45 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-07-09 15:49 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-07-10 14:13 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-07-10 14:35 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-07-11 13:36 UTC, merged